source "https://rubygems.org"

gem 'rake'
gem 'i18n'
gem 'active_support'
gem 'dm-mysql-adapter'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-constraints'
gem 'dm-aggregates'
gem 'dm-types'
gem 'dm-core'
gem 'moji'
gem 'systemu'
